### ISSUE TITLE
External links to EuropePMC 

### ISSUE THREAD

**Issue by dasaderi** [PREreview/rapid-prereview#125]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%24100%20Funded-%2300A156.svg" />](https://issuehunt.io/r/PREreview/rapid-prereview/issues/125)

From email conversation with Michele Ide-Smith ([EuropePMC](https://europepmc.org/)) January 22, 2020:

"We are keen to get links to reviews of preprints in https://www.prereview.org or https://outbreaksci.prereview.org/api onto preprint pages on Europe PMC. However the mechanism we were anticipating using was our External Links service, similar to PreLights and Peer Community In. See an example preprint and the 'reviews' section, with a link out to a Peer Community In review on here: http://europepmc.org/article/PPR/PPR91595#reviews.

To use our external links service a developer at your end would need to write a script to send us an XML file containing the links (e.g. DOI > review associations) along with a separate file containing your providers details. We would need to set you up with a provider ID and access to send these files by FTP. I think I sent this link before, but you can find out more details here: http://europepmc.org/LabsLink."

@jheretic @harumhelmy @rudietuesdays  how doable is this? We would love to get this set up by July as it's one of the main ask of a potential funder.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $100.00)

- [<img src='https://avatars1.githubusercontent.com/u/39268982?v=4' alt='prereview' width=24 height=24> prereview](https://issuehunt.io/u/prereview) ($100.00)

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/PREreview/rapid-prereview/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by harumhelmy** [comment]
Hi all! So if I'm understanding correctly, we just want to provide EuropePMC with links to preprints that have reviews and/or requests for reviews on OSrPRE, right? 

The query string to `GET` the first batch of preprints on OSrPRE is `https://outbreaksci.prereview.org/api/preprint/?q=*:*&sort=%5B%22-dateLastReview%3Cnumber%3E%22%2C%22-score%3Cnumber%3E%22%2C%22-datePosted%3Cnumber%3E%22%5D&include_docs=true&` and then you have to pass in the bookmark value to get the next batch, and so forth.

URLs to preprints (and their reviews and/or requests) on OSrPRE is always http://outbreaksci.prereview.org/<preprint DOI>

**Comment by jheretic** [comment]
For some additional context for anyone who might want to take on this issue:

* Since we are currently working on a new API backend, rather than trying to rework the existing API we want to implement a script which will fetch data using multiple calls to the existing API and synthesize it into multiple formats. Documentation on the existing API is at https://outbreaksci.prereview.org/api.
* One of those output formats would be the EuropePMC XML format linked above.
* We're currently working on the export script now, if you'd like to take that on instead let myself or @harumhelmy know. After Harum and I finish the first version of the script, this task will switch to just adding the EuropePMC XML output format to the script, for the same bounty.

**Comment by harumhelmy** [comment]
Closing this issue for now, WIP solution is at https://github.com/throneless-tech/prereview-feed
