### ISSUE TITLE
Workflow: When add a review from shell, move down viz to questions

### ISSUE THREAD

**Issue by dasaderi** [PREreview/rapid-prereview#54]
I noticed that when I clicked "Add a Review" button from shell view, I don't see any change occur and I thought it was not responding, while in fact it did show the questions at the bottom. Perhaps it would be useful to have the question scroll up to top of form frame?

**Comment by majohansson** [comment]
Good idea

**Comment by halmos** [comment]
@dasaderi, I want to clarify this issue and make sure we understand what is happening. The first visible graphic in the shell below the tab bar is a title indicating what you are looking at. So if you click on 'Read Reviews' the title shows 'Reviews' if you click on 'Add Review' the  title becomes 'Add a review' and the 'Add request' tab has the title 'Add a request for review'.

Can you confirm that you can see the title at the top of the shell content changing when you navigate between tabs?

**Comment by dasaderi** [comment]
@halmos yes I do see a title change. For some reasons I had not noticed that. But what's not visible is the bullet point form which is in a sense the most important part to see. So maybe we can do that when clicking add a review the window expands up a bit over the pdf?

**Comment by sballesteros** [comment]
I wonder if changing the text so it's really different is not the simplest fix here (resizing / scrolling is doable but fairly complex and hard to get right while also respecting user scroll preferences):

Right now we have: "Add a review" and "Add a request for review". Maybe if we were to use:
- Add a review
- Request for feedback
The tab transition would be much clearer as all the text will change. 
I think that part of the issue here is that given both text starts with "Add a" and end with "review" on a quick glance it's hard to realize that the text did change in between the tabs

**Comment by majohansson** [comment]
I think that's a good point, but I think "Request for feedback" doesn't really capture the process. Feedback implies back to the author whereas many requestors want reviews for other purposes; not to make it better, but to know whether they should use it or not.

Perhaps the following?

* Add review
* Request review

**Comment by sballesteros** [comment]
fixed with an animation
