### ISSUE TITLE
Remove the circle and number from the list items

### ISSUE THREAD

**Issue by dasaderi** [PREreview/rapid-prereview#56]
@majohansson, @georgiamoon, the interviewee, and I all feel like the summary number of reviews and requests is not useful and it can be confusing. So we would like it if you could remove it.

**Comment by sballesteros** [comment]
See also #57 as this is related to sorting (more soon).

**Comment by majohansson** [comment]
Yep. We like the trending metric, but think it should be mostly hidden. The number of reviews is likely the first interest point and the number of requests second and separate from that.

**Comment by sballesteros** [comment]
Here are a few reasons against that change:

- The circle in the badge represent the time elapsed since the first activity. This number is a key component of the score. Displaying this quantity helps to understand results like:

<img width="963" alt="Screen Shot 2019-12-13 at 8 11 43 AM" src="https://user-images.githubusercontent.com/1141327/70814404-42aee900-1d80-11ea-81f8-8de25765b934.png">

Here the reason the first one is trending is because it is "new" relative to the second one (which has much more activity). These kind of situations will be common as usage grows and we think that making clear how the ranking works is important. 

- As part of #57 we implemented a visual effect where hovering on a sort option highlights the element in the card that is at the origin of the sorting). This badge is important for this design to work so that each sorting option has a direct representation on the preprint card.

- We think that the major redesign that we did previously to give more room to the number of reviews and requests (now highlighted in red as requested) and downplay this "score badge" (now in light grey) strikes a good balance between highlighting the information you want and giving access to information that will be more useful as the usage grows and sort ambiguity arise.

- This is the kind of feature for which feedback are hard to get given it's a feature that only make sense after repeated exposure and under usage data that we don't know yet (usage data will be critical to understand how the scoring algorithm behaves. We haven't discussed and tried to tweak the parameters of this algorithm yet etc. 

- There are several implication with the extensions that we should keep in mind (I can detail if helpful). 

Our recommendation is to wait for more usage data before making a decision leading to the removal of a significant feature that we feel is a key part of the overall design. As of now it is really hard to predict what the home page will look like and how the number of requests and reviews will balance (imagine if there was an integration with bioRxiv so users can request feedback when they submit, that will lead to a lot of request on the page, the algorithm will be critical so that the homepage remains relevant for reviews too. Hacker News illustrate a case where the sorting algo works really well, our intent here was to introduce subtle design to demystify it.)

**Comment by sballesteros** [comment]
FWIW we tried the hourglass approach but it's not really working: in our case the amount of sand in the hourglass varies in between entries (and sand can be re-added to the hourglass at any time).
The current circle is a better representation as it illustrates 1 / (time_ellapsed + 1) ^g which is guaranteed to go from 1 -> 0 as time_ellapsed goes from 0 -> Infinity.

**Comment by dasaderi** [comment]
Okay. What about making the circle red? Nobody from the interviews got the decay. The contrast between greys is not enough. But we can leave this to future-dev if you want.

**Comment by halmos** [comment]
i will play with the colors to see if we can make it more apparent.
