### ISSUE TITLE
Did Not Connect: Potential Security Issue message when clicking on notification email link 

### ISSUE THREAD

**Issue by dasaderi** [PREreview/rapid-prereview#72]
When I click on any links from a notification email I get this message on Firefox:
"Did Not Connect: Potential Security Issue"

**Comment by sballesteros** [comment]
@dasaderi  i think this happens because someone enabled tracking on sendgrid:
<img width="1471" alt="Screen Shot 2020-01-29 at 8 59 20 AM" src="https://user-images.githubusercontent.com/1141327/73378611-b72ce100-4275-11ea-8d56-d36e8408215f.png">
With this setting, all the urls of the emails are being rewritten.

**Comment by sballesteros** [comment]
i deactivated the tracking hopefully that fixes it

**Comment by dasaderi** [comment]
Yes, it did. Thank you @sballesteros.
